import { adminLayout, esc, blockPreview, monacoEditorHTML, MONACO, MONACO_BASE } from './layout';

export const sections = (plugin: any, secList: any[]) => adminLayout({
  title:`${plugin.name} - 章节`,active:'plugins',
  body:`<h1 class="page-title">${esc(plugin.name)} — 章节管理</h1>
<a href="/admin/plugins/${plugin.id}/editor" class="btn btn-outline">← 返回编辑器</a>
<div class="card" style="margin-top:12px"><h3 id="sf-title">新建章节</h3>
<form id="sf"><input type="hidden" id="sf-id"/><div class="form-row"><div class="form-group"><label>名称（中文）</label><input id="sf-title-val" required/></div><div class="form-group"><label>Slug</label><input id="sf-slug" required/></div><div class="form-group"><label>排序</label><input id="sf-sort" type="number" value="0"/></div></div>
<div class="btn-group"><button type="submit" class="btn btn-primary" id="sf-btn">创建章节</button><button type="button" class="btn btn-outline" id="sf-cancel" style="display:none" onclick="resetSF()">取消</button></div></form></div>
<div id="section-list">${secList.length===0?'<div class="empty-state"><p>暂无章节</p></div>':''}${secList.map((s:any)=>`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><strong>${esc(s.titleZh||s.slug)}</strong><code style="font-size:11px;margin-left:8px;color:var(--muted)">#${esc(s.slug)}</code></div><div class="btn-group"><button class="btn btn-outline btn-sm" onclick='editS(${JSON.stringify(s)})'>编辑</button><button class="btn btn-danger btn-sm" onclick="delS(${s.id})">删除</button></div></div></div>`).join('')}</div>
<script>function resetSF(){document.getElementById('sf-id').value='';document.getElementById('sf-btn').textContent='创建章节';document.getElementById('sf-cancel').style.display='none';document.getElementById('sf-title').textContent='新建章节';document.getElementById('sf').reset();}
function editS(s){document.getElementById('sf-id').value=s.id;document.getElementById('sf-title-val').value=s.titleZh||s.slug;document.getElementById('sf-slug').value=s.slug;document.getElementById('sf-sort').value=s.sortOrder;document.getElementById('sf-btn').textContent='保存修改';document.getElementById('sf-cancel').style.display='';document.getElementById('sf-title').textContent='编辑章节';window.scrollTo(0,0);}
async function delS(id){if(!confirm('删除该章节？'))return;await fetch('/api/admin/sections/'+id,{method:'DELETE'});location.reload();}
document.getElementById('sf').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('sf-id').value;const d={pluginId:${plugin.id},titleZh:document.getElementById('sf-title-val').value,titleEn:document.getElementById('sf-title-val').value,slug:document.getElementById('sf-slug').value,sortOrder:Number(document.getElementById('sf-sort').value)};await fetch(id?'/api/admin/sections/'+id:'/api/admin/sections',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});location.reload();});
</script>`,
});

export const editSection = (section: any, blocks: any[]) => adminLayout({
  title:section.titleZh||section.slug,active:'plugins',
  head:`<link rel="preconnect" href="https://cdn.bootcdn.net"><script src="${MONACO_BASE}loader.js"></script>`,
  body:`<h1 class="page-title">${esc(section.titleZh||section.slug)} <code style="font-size:14px;font-weight:400;color:var(--muted)">#${esc(section.slug)}</code></h1>
<div class="btn-group" style="margin-bottom:14px"><a href="/admin/plugins/${section.pluginId}/editor" class="btn btn-outline btn-sm">← 返回编辑器</a></div>
<div id="block-list">${blocks.length===0?'<div class="empty-state"><p>暂无内容块</p></div>':blocks.map((b:any)=>`<div class="block-item"><div class="block-header"><span class="block-type-badge">${b.type}</span><span class="block-preview">${esc(blockPreview(b.type,b.contentJson))}</span><div class="btn-group"><button class="btn btn-outline btn-sm" onclick="editBlock(${b.id})">编辑</button><button class="btn btn-danger btn-sm" onclick="delB(${b.id})">删除</button></div></div></div>`).join('')}</div>
<div class="card"><h3 id="eb-title">添加内容块</h3><form id="eb-form"><input type="hidden" id="eb-id"/><div class="form-group"><label>类型</label><select id="eb-type" onchange="switchType(this.value)"><option value="html">HTML</option><option value="code">Code</option><option value="text">Text (i18n)</option><option value="callout">Callout (i18n)</option></select></div>
<div id="eb-html"><div class="form-group"><label>内容</label>${monacoEditorHTML('eb-editor',false,'','html')}</div></div>
<div id="eb-code" style="display:none"><div class="form-row"><div class="form-group"><label>语言</label><input id="eb-lang" value="cpp"/></div></div><div class="form-group"><label>代码</label>${monacoEditorHTML('eb-code-editor',false,'','cpp')}</div></div>
<div id="eb-text" style="display:none"><div class="form-row"><div class="form-group"><label>中文</label><textarea id="eb-text-zh" rows="3"></textarea></div><div class="form-group"><label>English</label><textarea id="eb-text-en" rows="3"></textarea></div></div></div>
<div class="btn-group" style="margin-top:8px"><button type="submit" class="btn btn-primary" id="eb-btn">创建</button><button type="button" class="btn btn-outline" id="eb-cancel" style="display:none" onclick="cancelEdit()">取消</button></div></form></div>
<script>require.config({paths:{vs:'${MONACO}'}});require(['vs/editor/editor.main'],function(){var he,ce;function _moveEditor(t){var s=t==='edit'?document.getElementById('eb-editor'):document.getElementById('eb-code-editor');if(s&&window['_m_'+s.id]){window['_m_'+s.id].layout();}}function editBlock(id){var b=${JSON.stringify(blocks)}.find(function(x){return x.id===id;});if(!b)return;document.getElementById('eb-id').value=b.id;document.getElementById('eb-type').value=b.type;document.getElementById('eb-btn').textContent='保存修改';document.getElementById('eb-cancel').style.display='';document.getElementById('eb-title').textContent='编辑内容块';switchType(b.type);_populate(b);}
function startAdd(){cancelEdit();document.getElementById('eb-title').textContent='添加内容块';}
function cancelEdit(){document.getElementById('eb-id').value='';document.getElementById('eb-form').reset();document.getElementById('eb-btn').textContent='创建';document.getElementById('eb-cancel').style.display='none';document.getElementById('eb-title').textContent='添加内容块';switchType('html');}
function _populate(b){var c={};try{c=JSON.parse(b.contentJson||'{}');}catch(e){}switch(b.type){case'html':if(window['_m_eb-editor'])window['_m_eb-editor'].setValue(c.html||'');break;case'code':document.getElementById('eb-lang').value=c.language||'cpp';if(window['_m_eb-code-editor'])window['_m_eb-code-editor'].setValue(c.code||'');break;case'text':case'callout':document.getElementById('eb-text-zh').value=c.textZh||'';document.getElementById('eb-text-en').value=c.textEn||'';break;}}
function switchType(t){['eb-html','eb-code','eb-text'].forEach(function(id){document.getElementById(id).style.display='none';});if(t==='html')document.getElementById('eb-html').style.display='';if(t==='code')document.getElementById('eb-code').style.display='';if(t==='text'||t==='callout')document.getElementById('eb-text').style.display='';setTimeout(function(){_moveEditor('edit');},100);}
async function delB(id){if(!confirm('删除该内容块？'))return;await fetch('/api/admin/blocks/'+id,{method:'DELETE'});location.reload();}
function getContent(){var t=document.getElementById('eb-type').value;if(t==='html'&&window['_m_eb-editor'])return window['_m_eb-editor'].getValue();if(t==='code'&&window['_m_eb-code-editor'])return window['_m_eb-code-editor'].getValue();return'';}
document.getElementById('eb-form').addEventListener('submit',async function(e){e.preventDefault();var id=document.getElementById('eb-id').value;var t=document.getElementById('eb-type').value;var data={sectionId:${section.id},type:t,sortOrder:${blocks.length}};if(t==='html')data.contentJson=JSON.stringify({html:getContent()});else if(t==='code')data.contentJson=JSON.stringify({language:document.getElementById('eb-lang').value,code:getContent()});else if(t==='text'||t==='callout')data.contentJson=JSON.stringify({textZh:document.getElementById('eb-text-zh').value,textEn:document.getElementById('eb-text-en').value});await fetch(id?'/api/admin/blocks/'+id:'/api/admin/blocks',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});location.reload();});
});</script>`,
});
